DROP SEQUENCE users_seq CASCADE;
DROP SEQUENCE tasks_seq CASCADE;
DROP SEQUENCE teams_seq CASCADE;

DROP TABLE "users" CASCADE;
DROP TABLE "tasks" CASCADE;
DROP TABLE "teams" CASCADE;
DROP TABLE "teams_tasks" CASCADE;
DROP TABLE "session" CASCADE;